[build]
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "http://panel-legal.jhonaley.net:4282/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
